name: Debug Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: List semua file
        run: ls -la
      
      - name: Cek file gradlew
        run: |
          if [ -f "gradlew" ]; then
            echo "✅ gradlew FOUND"
            cat gradlew | head -5
          else
            echo "❌ gradlew NOT FOUND"
            exit 1
          fi
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Chmod gradlew
        run: chmod +x gradlew
      
      - name: Build
        run: ./gradlew assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
